name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "docs/**"
    tags: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - uses: extractions/setup-just@v3
      - name: Install LibAacgm.jl
        run: just install && just install_lib docs
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
